[package]
name = "opensync-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
reqwest = { version = "0.13.2", features = ["blocking"] }
tar = "0.4"
clipboard-watcher = "0.2.1"
tokio = { version = "1.49.0", features = ["full"] }
futures = "0.3.32"
env_logger = "0.11.10"
log = "0.4.29"
arboard = "3"
