[package]
name = "cli_app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = "4.5.60"
config = "0.15.19"
dotenv = "0.15.0"
serde = { version = "1", features = ["derive"] }
axum = "0.8.8"
tokio = { version = "1.49.0", features = ["full"] }
tokio-util = { version = "0.7.18", features = ["io-util"] }
arc-swap = "1.8.2"
tracing = { version = "0.1.44", features = ["log"] }
tracing-log = { version = "0.2" }
tracing-subscriber = { version = "0.3.22", features = ["registry", "env-filter"] }
tower-http = { version = "0.6.8", features = ["trace"] }
chrono = { version = "0.4.34", features = ["serde"] }
jsonwebtoken = "8.3.0"
http = "1"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
