[package]
name = "opensync-desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
tao = "0.35.0"
tray-icon = "0.22.1"
clipboard = { path = "../../crates/clipboard" }
tokio = { version = "1.49.0", features = ["full"] }
rust_socketio = { version = "*", features = ["async"] }
futures-util = "0.3.32"
image = { version = "0.25.8", default-features = false, features = ["png", "ico"] }
sync = { path = "../../crates/sync" }
storage = { path = "../../crates/storage" }
egui = "0.31.1"
egui_glow = "0.31.1"
glow = "0.16.0"
raw-window-handle = "0.6.2"
glutin = "0.32.1"
